MinGW: implement compat/signal.h
MinGW does not define SIGUSR1 and SIGUSR2.
Implement a compatibility header for the
system's signal.h, and add missing
definitions from the POSIX standard.

Solves build error:
```
BasicActions.cc: In member function
  'virtual void Mgr::ReconfigureAction::dump(...)'
  error: 'SIGHUP' was not declared in this scope
  error: 'SIGUSR1' was not declared in this scope
```