Mingw: Fix aiops_win32.cc
Missing includes, missing prototypes in
compat/os/mingw.h, type mismatches in some
local variables.

On top of it, Applied some AAA, and used
PackableStream instead of storeAppendPrintf

Examples of errors fixed:

```
src/DiskIO/DiskThreads/aiops_win32.cc: In function 'void* squidaio_xmalloc(int)':
src/DiskIO/DiskThreads/aiops_win32.cc:161:17: error: invalid use of incomplete type 'class Mem::Allocator'
  161 |         p = pool->alloc();
      |                 ^~
src/mem/AllocatorProxy.h:14:7: note: forward declaration of 'class Mem::Allocator'
   14 | class Allocator;
      |       ^~~~~~~~~

src/DiskIO/DiskThreads/aiops_win32.cc: In function 'void squidaio_xfree(void*, int)':
src/DiskIO/DiskThreads/aiops_win32.cc:184:13: error: invalid use of incomplete type 'class Mem::Allocator'
  184 |         pool->freeOne(p);
      |             ^~
src/DiskIO/DiskThreads/aiops_win32.cc: In function 'void squidaio_init()':
src/DiskIO/DiskThreads/aiops_win32.cc:278:19: error: comparison of integer expressions of different signedness: 'int' and 'size_t' {aka 'long long unsigned int'} [-Werror=sign-compare]
  278 |     for (i = 0; i < NUMTHREADS; ++i) {

src/DiskIO/DiskThreads/aiops_win32.cc: In function 'void squidaio_queue_request(squidaio_request_t*)':
src/DiskIO/DiskThreads/aiops_win32.cc:590:27: error: comparison of integer expressions of different signedness: 'int' and 'size_t' {aka 'long long unsigned int'} [-Werror=sign-compare]
  590 |     if (request_queue_len > MAGIC1) {

src/DiskIO/DiskThreads/aiops_win32.cc: In function 'void squidaio_do_read(squidaio_request_t*)':
src/DiskIO/DiskThreads/aiops_win32.cc:782:9: error: 'WIN32_maperror' was not declared in this scope
  782 |         WIN32_maperror(GetLastError());
      |         ^~~~~~~~~~~~~~
```